name: PHPStan

on: [pull_request, push]

jobs:
  setup:
    uses: ./.github/workflows/setup-php.yaml

  analyse:
    needs: setup

    name: PHPStan

    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}

      - name: Load
        run: |
          docker load -i ${{ needs.setup.outputs.tar }}

      - name: Run
        run: |
          docker compose -f compose.ci.yaml run --rm php php -v
          # docker compose -f compose.ci.yaml run --rm php php artisan -v
