name: PHPStan

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  setup:
    uses: ./.github/workflows/setup-php.yaml

  analyse:
    needs: setup

    name: PHPStan

    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}

      - name: Cache
        id: cache
        uses: actions/cache@v4
        with:
          path: ${{ needs.setup.outputs.path }}
          key: ${{ needs.setup.outputs.key }}

      - name: Load
        run: |
          docker load -i ${{ needs.setup.outputs.tar }}

      - name: Run
        run: |
          docker compose -f compose.ci.yaml run --rm php php -v
          docker compose -f compose.ci.yaml run --rm php php artisan -v
