name: PHPUnit

on: pull_request

jobs:
  # setup-php:
  #   uses: ./.github/workflows/setup-php.yaml

  test:
    # needs:
    #   - setup-php

    # name: PHPUnit (PHP ${{ needs.setup-php.outputs.php-version }})

    runs-on: ubuntu-latest

    steps:
      - name: echo
        run: echo "Hello"
      # - name: Create Database
      #   shell: bash
      #   run: |
      #     cd src
      #     mkdir -p database
      #     touch database/database.sqlite

      # - name: Setup env
      #   shell: bash
      #   run: |
      #     cd src
      #     cp .env.testing.example .env.testing
      #     php artisan key:generate --env=testing

      # - name: Migrate
      #   shell: bash
      #   run: |
      #     cd src
      #     php artisan migrate --env=testing

      # - name: Run PHPUnit
      #   run: |
      #     cd src
      #     composer test-all
